name: Build API

on:
  push:
    paths:
      - 'api/**'
  pull_request:
    paths:
      - 'api/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    environment: dev

    defaults:
      run:
        working-directory: api

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run tests
        run: coverage run -m pytest

      - name: Generate coverage report
        run: coverage xml

      - name: Produce coverage summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: api/coverage.xml
          fail_below_min: 80
          format: text
          thresholds: '70 80'

  formatter:
    runs-on: ubuntu-20.04
    environment: dev

    defaults:
      run:
        working-directory: api

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Check formatting
        run: black --check .

  template:
    runs-on: ubuntu-20.04
    environment: dev
    env:
      APP_STAGE: ${{ vars.APP_STAGE }}
      AWS_REGION: ${{ vars.AWS_REGION }}

    defaults:
      run:
        working-directory: api

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Install Node.js version 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Check CloudFormation template
        run: cdk synth --all
