name: Build UI

on:
  push:
    paths:
      - 'ui/**'
  pull_request:
    paths:
      - 'ui/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    environment: dev
    env:
      REACT_APP_API_URL: ${{ vars.REACT_APP_API_URL }}

    defaults:
      run:
        working-directory: ui

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js version 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Node.js install
        run: npm ci

      - name: Build
        run: npm run build

  test:
    runs-on: ubuntu-20.04
    environment: dev
    needs: [build]
    env:
      REACT_APP_API_URL: ${{ vars.REACT_APP_API_URL }}

    defaults:
      run:
        working-directory: ui

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js version 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Node.js install
        run: npm ci

      - name: Test
        run: npm run test

  lint:
    runs-on: ubuntu-20.04
    environment: dev
    needs: [ build ]
    env:
      REACT_APP_API_URL: ${{ vars.REACT_APP_API_URL }}

    defaults:
      run:
        working-directory: ui

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js version 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Node.js install
        run: npm ci

      - name: ESLint check
        run: npm run lint